//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUEXEOTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CT_PhieuThue
    {
        public int MaCTPT { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<int> MaPT { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrangThue { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual tb_PhieuThue tb_PhieuThue { get; set; }
        public virtual tb_Xe tb_Xe { get; set; }
    }
}
