//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUEXEOTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TaiKhoan
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> CapDoQuyen { get; set; }
        public Nullable<int> MANV { get; set; }
        public string Avatar { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
