//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUEXEOTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Xe()
        {
            this.tb_CT_PhieuThue = new HashSet<tb_CT_PhieuThue>();
        }
    
        public int MaXe { get; set; }
        public string TenXe { get; set; }
        public Nullable<int> SoChoNgoi { get; set; }
        public Nullable<decimal> GiaThue { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaLoaiXe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CT_PhieuThue> tb_CT_PhieuThue { get; set; }
        public virtual tb_LoaiXe tb_LoaiXe { get; set; }
    }
}
